name: svg
author: Matan Lurey <matanl@google.com>
description: A pure-dart implementation of an SVG parser.
homepage: https://github.com/matanlurey/svg
version: 0.1.0
dependencies:
#  dart_builder: ">=0.1.0 <0.2.0"
  petitparser: ">=2.0.0 <3.0.0"
  quiver: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: any
